### ISSUE TITLE
ModuleNotFoundError: No module named 'model_recon_3layers_robustness' 

### ISSUE THREAD

**Issue by lrrll** [zztianzz/PF-Net-Point-Fractal-Network#10]
when i run "show_FPNet.py"
i don't know why it is wrong, please tell me how to solve it, thanks.

**Comment by zztianzz** [comment]
Use the latest file 'show_recon.py' to avoid this error.

**Comment by lrrll** [comment]
thank you, but when i run 'show_recon.py' it came the problem following:
Namespace(batchSize=1, beta1=0.9, crop_point_num=512, cropmethod='random_center', cuda=False, dataroot='dataset/train', drop=0.2, each_scales_size=1, learning_rate=0.0002, manualSeed=None, nc=3, netD='', netG='Checkpoint/point_netG.pth', ngpu=2, niter=300, num_scales=3, pnum=2048, point_scales_list=[2048, 1024, 512], weight_decay=0.001, workers=2, wtl2=0.9)
Traceback (most recent call last):
  File "show_recon.py", line 64, in <module>
    test_dset = shapenet_part_loader.PartDataset( root='./dataset/shapenetcore_part/shapenetcore_partanno_segmentation_benchmark_v0/',classification=True, class_choice='Airplane', npoints=opt.pnum, split='test')
  File "/home/ouc/lrr/PF-Net-Point-Fractal-Network-master/shapenet_part_loader.py", line 24, in __init__
    with open(self.catfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/shapenetcore_part/shapenetcore_partanno_segmentation_benchmark_v0/synsetoffset2category.txt'
  but that .txt is really exist

**Comment by zztianzz** [comment]
You change the initial path into:'./dataset/shapenetcore_part/shapenetcore_partanno_segmentation_benchmark_v0/'. So maybe you also need to change the path in shape_part_loader.py line 13.

**Comment by lrrll** [comment]
'shape_part_loader.py' line 13:dataset_path=os.path.abspath(os.path.join(BASE_DIR, '../dataset/shapenet_part/shapenetcore_partanno_segmentation_benchmark_v0/'))
'show_recon.py' line 64:test_dset = shapenet_part_loader.PartDataset( root='./dataset/shapenetcore_part/shapenetcore_partanno_segmentation_benchmark_v0/',classification=True, class_choice='Airplane', npoints=opt.pnum, split='test')

so i don't know where the problem is

**Comment by zztianzz** [comment]
I didn't meet this problem before. Can you train the network? Maybe you can copy the path from the train file.

**Comment by bubuBlack** [comment]
> Use the latest file 'show_recon.py' to avoid this error.

when I run the file'show_recon.py', i met the error:
ModuleNotFoundError: No module named 'model_FPNet'
Have i miss some steps?
