### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Trained_Model/point_netG0.pth'

### ISSUE THREAD

**Issue by lrrll** [zztianzz/PF-Net-Point-Fractal-Network#4]
Traceback (most recent call last):
  File "Train_FPNet.py", line 340, in <module>
    'Trained_Model/point_netG'+str(epoch)+'.pth' )
  File "/home/ouc/.conda/envs/PF-Net/lib/python3.7/site-packages/torch/serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/ouc/.conda/envs/PF-Net/lib/python3.7/site-packages/torch/serialization.py", line 141, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Trained_Model/point_netG0.pth'

I can't find the location of Trained_Model ,could you please tell me how to solve this problem.

**Comment by SkyeFromKindergarten** [comment]
You should first make a folder 'Trained_Model'.

Or you could add code to automatic make directory.

**Comment by zztianzz** [comment]
Please add a file named "Checkpoint" before training and use show_recon.py to generate txt files

**Comment by lrrll** [comment]
> Please add a file named "Checkpoint" before training and use show_recon.py to generate txt files

Traceback (most recent call last):
  File "show_recon.py", line 72, in <module>
    point_netG.load_state_dict(torch.load(opt.netG,map_location=lambda storage, location: storage)['state_dict'])   
  File "/home/ouc/.conda/envs/PF-Net/lib/python3.7/site-packages/torch/serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ouc/lrr/PF-Net-Point-Fractal-Network-master/Checkpoint/point_netG.pth'

hello i created a file named'Checkpoint' but it showed couldn‘t find

**Comment by zztianzz** [comment]
> > Please add a file named "Checkpoint" before training and use show_recon.py to generate txt files
> 
> Traceback (most recent call last):
> File "show_recon.py", line 72, in
> point_netG.load_state_dict(torch.load(opt.netG,map_location=lambda storage, location: storage)['state_dict'])
> File "/home/ouc/.conda/envs/PF-Net/lib/python3.7/site-packages/torch/serialization.py", line 365, in load
> f = open(f, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: '/home/ouc/lrr/PF-Net-Point-Fractal-Network-master/Checkpoint/point_netG.pth'
> 
> hello i created a file named'Checkpoint' but it showed couldn‘t find

This problem has been fixed. I think you may need to download the hole package again to avoid some path or  ' No such file or directory' errors

**Comment by lrrll** [comment]
> > > Please add a file named "Checkpoint" before training and use show_recon.py to generate txt files
> > 
> > 
> > Traceback (most recent call last):
> > File "show_recon.py", line 72, in
> > point_netG.load_state_dict(torch.load(opt.netG,map_location=lambda storage, location: storage)['state_dict'])
> > File "/home/ouc/.conda/envs/PF-Net/lib/python3.7/site-packages/torch/serialization.py", line 365, in load
> > f = open(f, 'rb')
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/ouc/lrr/PF-Net-Point-Fractal-Network-master/Checkpoint/point_netG.pth'
> > hello i created a file named'Checkpoint' but it showed couldn‘t find
> 
> This problem has been fixed. I think you may need to download the whole package again to avoid some path or ' No such file or directory' errors

hello i see it has been upgraded,but the problem is always there.
say "No such file or directory:Checkpoint/point_netG.pth" i want know whether it has something to run before train the show_recon or Train_PFNet.py

**Comment by lrrll** [comment]
> You should first make a folder 'Trained_Model'.
> 
> Or you could add code to automatic make directory.

hello the problem is always,it means it could not find the point_netG.pth, whether i dont download something?

**Comment by mingmou123** [comment]
> > You should first make a folder 'Trained_Model'.
> > Or you could add code to automatic make directory.
> 
> hello the problem is always,it means it could not find the point_netG.pth, whether i dont download something?

I have met the same problem, can you tell me how to slove it? thanks.

**Comment by ndquan99** [comment]
same problem. How can i fix it?

**Comment by Sakura0v01** [comment]
same problem. How can i fix it?
