### ISSUE TITLE
怎么使用自己的数据测试？

### ISSUE THREAD

**Issue by weishuoycbb** [zztianzz/PF-Net-Point-Fractal-Network#5]
我在使用自己的点云文件时（大约6k个点）测试时，遇到了这么一个错。用test_one里的点云测试是ok的。
![image](https://user-images.githubusercontent.com/43461329/77887666-8ed55900-729d-11ea-9635-32cd956333f1.png)

**Comment by zztianzz** [comment]
请问遇到了什么错误呢，我这里没有显示出来

**Comment by weishuoycbb** [comment]
Traceback (most recent call last):
  File "Test_csv.py", line 79, in <module>
    fake_center1,fake_center2,fake=point_netG(input_cropped)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/ws~PFNet_36251407/model_FPNet.py", line 130, in forward
    x = self.latentfeature(x)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/ws~PFNet_36251407/model_FPNet.py", line 61, in forward
    latentfeature = torch.cat(outs,2)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 4 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62

**Comment by zztianzz** [comment]
你的输入点云转成Tensor之后的维度是什么？



At 2020-03-31 08:48:17, "weishuoycbb" <notifications@github.com> wrote:

Traceback (most recent call last):
File "Test_csv.py", line 79, in
fake_center1,fake_center2,fake=point_netG(input_cropped)
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
return self.module(*inputs[0], **kwargs[0])
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/root/wsPFNet_36251407/model_FPNet.py", line 130, in forward
x = self.latentfeature(x)
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/root/wsPFNet_36251407/model_FPNet.py", line 61, in forward
latentfeature = torch.cat(outs,2)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 4 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62

**Comment by weishuoycbb** [comment]
我在Test_csv.py的这个地方
input_cropped1 = np.loadtxt(opt.infile,delimiter=',')
input_cropped1 = torch.FloatTensor(input_cropped1)
print(input_cropped1.size())
torch.Size([6000, 3])

**Comment by weishuoycbb** [comment]
我刚才找了个1000多个点的稀疏点云，补到2048个点，跑通了。。。。。。

**Comment by zztianzz** [comment]
If you want to test your pointcloud. You need to change the first parameter 2048 of "point_scales_list" to match the number of your input points.
